[Settings]

[context.production]
  command = "bundle install && bundle exec jekyll build"

[context.deploy-preview]
  CONTEXT = deploy-preview
  command = "CONTEXT bundle install && bundle exec jekyll build"